[package]
name = "sl-messages"
version = "1.3.0-pre.2"
license-file = "../../LICENSE"
edition = "2021"
rust-version = "1.88"
repository = "https://github.com/silence-laboratories/sl-crypto"
description = "Message exchange for MPC protocols"

[dependencies]
bytemuck = { workspace = true, features = [ "derive", "min_const_generics" ] }
bytes = { workspace = true }
derivation-path = { workspace = true, optional = true }
fastwebsockets = { workspace = true, features = ["unstable-split"], optional = true }
sha2 = { workspace = true }
signature = { workspace = true, optional = true }
sl-msg-encrypt = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
x25519-dalek = { workspace = true, features = ["alloc", "reusable_secrets", "zeroize"], optional = true }
zeroize = { workspace = true, features = [ "derive" ] }

[dev-dependencies]
rand = { workspace = true, features = ["std", "std_rng"] }
rand_chacha = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "time"] }

[features]
default = ["std", "signed", "encrypted"]
std = []
encrypted = ["dep:sl-msg-encrypt", "sl-msg-encrypt/aead-x25519", "sl-msg-encrypt/chacha20poly1305"]
aead-p256 = ["encrypted", "sl-msg-encrypt/aead-p256"]
mux = [ "std", "tokio/macros", "tokio/sync", "tokio/rt" ]
fast-ws = [ "std", "fastwebsockets", "tokio/macros", "tokio/sync", "tokio/rt" ]
signed = ["dep:signature"]
setup = ["signed", "dep:derivation-path", "dep:x25519-dalek"]
