[package]
name = "sl-mpc-mate"
version = "1.1.1"
edition = "2021"
license-file = "../../LICENSE"
description = "Utilities for secure multi-party computation"
rust-version = "1.88"
repository = "https://github.com/silence-laboratories/sl-crypto"

[dependencies]
base64 = { workspace = true, features = ["alloc"] }
bs58 = { workspace = true, features = ["alloc"] }
derivation-path = { workspace = true }
elliptic-curve = { workspace = true, features = ["arithmetic", "sec1"] }
hex = { workspace = true, features = ["alloc"] }
hmac = { workspace = true }
rand_core = { workspace = true }
ripemd = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true, features = ["const-generics"] }
zeroize = { workspace = true, features = ["derive"] }
thiserror = { workspace = true, optional = true }

rayon = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }

[dev-dependencies]
ciborium = { workspace = true }
k256 = { workspace = true, features = ["arithmetic"] }
rand = { workspace = true, features = ["std", "std_rng"] }

[features]
default = ["std"]
std = ["dep:thiserror"]
rayon = ["std", "dep:rayon"]
serde = ["dep:serde", "k256/serde", "elliptic-curve/serde"]
